/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as PublicImovelSlugRouteImport } from './routes/_public.imovel.$slug'
import { Route as AdminAdminReservasRouteImport } from './routes/_admin.admin.reservas'
import { Route as AdminAdminPropriedadesRouteImport } from './routes/_admin.admin.propriedades'
import { Route as AdminAdminReservasIdRouteImport } from './routes/_admin.admin.reservas.$id'
import { Route as AdminAdminPropriedadesNovaRouteImport } from './routes/_admin.admin.propriedades.nova'
import { Route as AdminAdminPropriedadesIdEditarRouteImport } from './routes/_admin.admin.propriedades.$id.editar'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const PublicImovelSlugRoute = PublicImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminReservasRoute = AdminAdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPropriedadesRoute = AdminAdminPropriedadesRouteImport.update({
  id: '/propriedades',
  path: '/propriedades',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReservasIdRoute = AdminAdminReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminReservasRoute,
} as any)
const AdminAdminPropriedadesNovaRoute =
  AdminAdminPropriedadesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AdminAdminPropriedadesRoute,
  } as any)
const AdminAdminPropriedadesIdEditarRoute =
  AdminAdminPropriedadesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AdminAdminPropriedadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/propriedades': typeof AdminAdminPropriedadesRouteWithChildren
  '/admin/reservas': typeof AdminAdminReservasRouteWithChildren
  '/imovel/$slug': typeof PublicImovelSlugRoute
  '/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/propriedades': typeof AdminAdminPropriedadesRouteWithChildren
  '/admin/reservas': typeof AdminAdminReservasRouteWithChildren
  '/imovel/$slug': typeof PublicImovelSlugRoute
  '/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/propriedades': typeof AdminAdminPropriedadesRouteWithChildren
  '/_admin/admin/reservas': typeof AdminAdminReservasRouteWithChildren
  '/_public/imovel/$slug': typeof PublicImovelSlugRoute
  '/_admin/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/_admin/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/_admin/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/propriedades'
    | '/admin/reservas'
    | '/imovel/$slug'
    | '/admin/propriedades/nova'
    | '/admin/reservas/$id'
    | '/admin/propriedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/propriedades'
    | '/admin/reservas'
    | '/imovel/$slug'
    | '/admin/propriedades/nova'
    | '/admin/reservas/$id'
    | '/admin/propriedades/$id/editar'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/_admin/admin'
    | '/admin/login'
    | '/_public/'
    | '/_admin/admin/propriedades'
    | '/_admin/admin/reservas'
    | '/_public/imovel/$slug'
    | '/_admin/admin/propriedades/nova'
    | '/_admin/admin/reservas/$id'
    | '/_admin/admin/propriedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/imovel/$slug': {
      id: '/_public/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof PublicImovelSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/reservas': {
      id: '/_admin/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminAdminReservasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/propriedades': {
      id: '/_admin/admin/propriedades'
      path: '/propriedades'
      fullPath: '/admin/propriedades'
      preLoaderRoute: typeof AdminAdminPropriedadesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reservas/$id': {
      id: '/_admin/admin/reservas/$id'
      path: '/$id'
      fullPath: '/admin/reservas/$id'
      preLoaderRoute: typeof AdminAdminReservasIdRouteImport
      parentRoute: typeof AdminAdminReservasRoute
    }
    '/_admin/admin/propriedades/nova': {
      id: '/_admin/admin/propriedades/nova'
      path: '/nova'
      fullPath: '/admin/propriedades/nova'
      preLoaderRoute: typeof AdminAdminPropriedadesNovaRouteImport
      parentRoute: typeof AdminAdminPropriedadesRoute
    }
    '/_admin/admin/propriedades/$id/editar': {
      id: '/_admin/admin/propriedades/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/propriedades/$id/editar'
      preLoaderRoute: typeof AdminAdminPropriedadesIdEditarRouteImport
      parentRoute: typeof AdminAdminPropriedadesRoute
    }
  }
}

interface AdminAdminPropriedadesRouteChildren {
  AdminAdminPropriedadesNovaRoute: typeof AdminAdminPropriedadesNovaRoute
  AdminAdminPropriedadesIdEditarRoute: typeof AdminAdminPropriedadesIdEditarRoute
}

const AdminAdminPropriedadesRouteChildren: AdminAdminPropriedadesRouteChildren =
  {
    AdminAdminPropriedadesNovaRoute: AdminAdminPropriedadesNovaRoute,
    AdminAdminPropriedadesIdEditarRoute: AdminAdminPropriedadesIdEditarRoute,
  }

const AdminAdminPropriedadesRouteWithChildren =
  AdminAdminPropriedadesRoute._addFileChildren(
    AdminAdminPropriedadesRouteChildren,
  )

interface AdminAdminReservasRouteChildren {
  AdminAdminReservasIdRoute: typeof AdminAdminReservasIdRoute
}

const AdminAdminReservasRouteChildren: AdminAdminReservasRouteChildren = {
  AdminAdminReservasIdRoute: AdminAdminReservasIdRoute,
}

const AdminAdminReservasRouteWithChildren =
  AdminAdminReservasRoute._addFileChildren(AdminAdminReservasRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminPropriedadesRoute: typeof AdminAdminPropriedadesRouteWithChildren
  AdminAdminReservasRoute: typeof AdminAdminReservasRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminPropriedadesRoute: AdminAdminPropriedadesRouteWithChildren,
  AdminAdminReservasRoute: AdminAdminReservasRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicImovelSlugRoute: typeof PublicImovelSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicImovelSlugRoute: PublicImovelSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
