/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PublicSobreRouteImport } from './routes/_public.sobre'
import { Route as PublicPropriedadesRouteImport } from './routes/_public.propriedades'
import { Route as PublicEventosRouteImport } from './routes/_public.eventos'
import { Route as PublicAnuncieRouteImport } from './routes/_public.anuncie'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as PublicRestaurantesIndexRouteImport } from './routes/_public.restaurantes.index'
import { Route as PublicPasseiosIndexRouteImport } from './routes/_public.passeios.index'
import { Route as PublicAtracoesIndexRouteImport } from './routes/_public.atracoes.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as PublicRestaurantesSlugRouteImport } from './routes/_public.restaurantes.$slug'
import { Route as PublicPasseiosSlugRouteImport } from './routes/_public.passeios.$slug'
import { Route as PublicImovelSlugRouteImport } from './routes/_public.imovel.$slug'
import { Route as PublicAtracoesSlugRouteImport } from './routes/_public.atracoes.$slug'
import { Route as AdminAdminSubmissoesRouteImport } from './routes/_admin.admin.submissoes'
import { Route as AdminAdminSobreRouteImport } from './routes/_admin.admin.sobre'
import { Route as AdminAdminReservasRouteImport } from './routes/_admin.admin.reservas'
import { Route as AdminAdminPropriedadesRouteImport } from './routes/_admin.admin.propriedades'
import { Route as AdminAdminInstagramRouteImport } from './routes/_admin.admin.instagram'
import { Route as AdminAdminHomeRouteImport } from './routes/_admin.admin.home'
import { Route as AdminAdminEventosRouteImport } from './routes/_admin.admin.eventos'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin.admin.configuracoes'
import { Route as AdminAdminCalendarioRouteImport } from './routes/_admin.admin.calendario'
import { Route as AdminAdminAtracoesRouteImport } from './routes/_admin.admin.atracoes'
import { Route as AdminAdminReservasIndexRouteImport } from './routes/_admin.admin.reservas.index'
import { Route as AdminAdminPropriedadesIndexRouteImport } from './routes/_admin.admin.propriedades.index'
import { Route as AdminAdminReservasNovaRouteImport } from './routes/_admin.admin.reservas.nova'
import { Route as AdminAdminReservasIdRouteImport } from './routes/_admin.admin.reservas.$id'
import { Route as AdminAdminPropriedadesNovaRouteImport } from './routes/_admin.admin.propriedades.nova'
import { Route as AdminAdminPropriedadesIdEditarRouteImport } from './routes/_admin.admin.propriedades.$id.editar'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPropriedadesRoute = PublicPropriedadesRouteImport.update({
  id: '/propriedades',
  path: '/propriedades',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventosRoute = PublicEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAnuncieRoute = PublicAnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRestaurantesIndexRoute = PublicRestaurantesIndexRouteImport.update({
  id: '/restaurantes/',
  path: '/restaurantes/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPasseiosIndexRoute = PublicPasseiosIndexRouteImport.update({
  id: '/passeios/',
  path: '/passeios/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAtracoesIndexRoute = PublicAtracoesIndexRouteImport.update({
  id: '/atracoes/',
  path: '/atracoes/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const PublicRestaurantesSlugRoute = PublicRestaurantesSlugRouteImport.update({
  id: '/restaurantes/$slug',
  path: '/restaurantes/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPasseiosSlugRoute = PublicPasseiosSlugRouteImport.update({
  id: '/passeios/$slug',
  path: '/passeios/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImovelSlugRoute = PublicImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAtracoesSlugRoute = PublicAtracoesSlugRouteImport.update({
  id: '/atracoes/$slug',
  path: '/atracoes/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminSubmissoesRoute = AdminAdminSubmissoesRouteImport.update({
  id: '/submissoes',
  path: '/submissoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSobreRoute = AdminAdminSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReservasRoute = AdminAdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPropriedadesRoute = AdminAdminPropriedadesRouteImport.update({
  id: '/propriedades',
  path: '/propriedades',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminInstagramRoute = AdminAdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminHomeRoute = AdminAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEventosRoute = AdminAdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCalendarioRoute = AdminAdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAtracoesRoute = AdminAdminAtracoesRouteImport.update({
  id: '/atracoes',
  path: '/atracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReservasIndexRoute = AdminAdminReservasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminReservasRoute,
} as any)
const AdminAdminPropriedadesIndexRoute =
  AdminAdminPropriedadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminPropriedadesRoute,
  } as any)
const AdminAdminReservasNovaRoute = AdminAdminReservasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminAdminReservasRoute,
} as any)
const AdminAdminReservasIdRoute = AdminAdminReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminReservasRoute,
} as any)
const AdminAdminPropriedadesNovaRoute =
  AdminAdminPropriedadesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AdminAdminPropriedadesRoute,
  } as any)
const AdminAdminPropriedadesIdEditarRoute =
  AdminAdminPropriedadesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AdminAdminPropriedadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/anuncie': typeof PublicAnuncieRoute
  '/eventos': typeof PublicEventosRoute
  '/propriedades': typeof PublicPropriedadesRoute
  '/sobre': typeof PublicSobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/atracoes': typeof AdminAdminAtracoesRoute
  '/admin/calendario': typeof AdminAdminCalendarioRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/eventos': typeof AdminAdminEventosRoute
  '/admin/home': typeof AdminAdminHomeRoute
  '/admin/instagram': typeof AdminAdminInstagramRoute
  '/admin/propriedades': typeof AdminAdminPropriedadesRouteWithChildren
  '/admin/reservas': typeof AdminAdminReservasRouteWithChildren
  '/admin/sobre': typeof AdminAdminSobreRoute
  '/admin/submissoes': typeof AdminAdminSubmissoesRoute
  '/atracoes/$slug': typeof PublicAtracoesSlugRoute
  '/imovel/$slug': typeof PublicImovelSlugRoute
  '/passeios/$slug': typeof PublicPasseiosSlugRoute
  '/restaurantes/$slug': typeof PublicRestaurantesSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/atracoes/': typeof PublicAtracoesIndexRoute
  '/passeios/': typeof PublicPasseiosIndexRoute
  '/restaurantes/': typeof PublicRestaurantesIndexRoute
  '/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/admin/reservas/nova': typeof AdminAdminReservasNovaRoute
  '/admin/propriedades/': typeof AdminAdminPropriedadesIndexRoute
  '/admin/reservas/': typeof AdminAdminReservasIndexRoute
  '/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/anuncie': typeof PublicAnuncieRoute
  '/eventos': typeof PublicEventosRoute
  '/propriedades': typeof PublicPropriedadesRoute
  '/sobre': typeof PublicSobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/atracoes': typeof AdminAdminAtracoesRoute
  '/admin/calendario': typeof AdminAdminCalendarioRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/eventos': typeof AdminAdminEventosRoute
  '/admin/home': typeof AdminAdminHomeRoute
  '/admin/instagram': typeof AdminAdminInstagramRoute
  '/admin/sobre': typeof AdminAdminSobreRoute
  '/admin/submissoes': typeof AdminAdminSubmissoesRoute
  '/atracoes/$slug': typeof PublicAtracoesSlugRoute
  '/imovel/$slug': typeof PublicImovelSlugRoute
  '/passeios/$slug': typeof PublicPasseiosSlugRoute
  '/restaurantes/$slug': typeof PublicRestaurantesSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/atracoes': typeof PublicAtracoesIndexRoute
  '/passeios': typeof PublicPasseiosIndexRoute
  '/restaurantes': typeof PublicRestaurantesIndexRoute
  '/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/admin/reservas/nova': typeof AdminAdminReservasNovaRoute
  '/admin/propriedades': typeof AdminAdminPropriedadesIndexRoute
  '/admin/reservas': typeof AdminAdminReservasIndexRoute
  '/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_public/anuncie': typeof PublicAnuncieRoute
  '/_public/eventos': typeof PublicEventosRoute
  '/_public/propriedades': typeof PublicPropriedadesRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/atracoes': typeof AdminAdminAtracoesRoute
  '/_admin/admin/calendario': typeof AdminAdminCalendarioRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/eventos': typeof AdminAdminEventosRoute
  '/_admin/admin/home': typeof AdminAdminHomeRoute
  '/_admin/admin/instagram': typeof AdminAdminInstagramRoute
  '/_admin/admin/propriedades': typeof AdminAdminPropriedadesRouteWithChildren
  '/_admin/admin/reservas': typeof AdminAdminReservasRouteWithChildren
  '/_admin/admin/sobre': typeof AdminAdminSobreRoute
  '/_admin/admin/submissoes': typeof AdminAdminSubmissoesRoute
  '/_public/atracoes/$slug': typeof PublicAtracoesSlugRoute
  '/_public/imovel/$slug': typeof PublicImovelSlugRoute
  '/_public/passeios/$slug': typeof PublicPasseiosSlugRoute
  '/_public/restaurantes/$slug': typeof PublicRestaurantesSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/atracoes/': typeof PublicAtracoesIndexRoute
  '/_public/passeios/': typeof PublicPasseiosIndexRoute
  '/_public/restaurantes/': typeof PublicRestaurantesIndexRoute
  '/_admin/admin/propriedades/nova': typeof AdminAdminPropriedadesNovaRoute
  '/_admin/admin/reservas/$id': typeof AdminAdminReservasIdRoute
  '/_admin/admin/reservas/nova': typeof AdminAdminReservasNovaRoute
  '/_admin/admin/propriedades/': typeof AdminAdminPropriedadesIndexRoute
  '/_admin/admin/reservas/': typeof AdminAdminReservasIndexRoute
  '/_admin/admin/propriedades/$id/editar': typeof AdminAdminPropriedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/eventos'
    | '/propriedades'
    | '/sobre'
    | '/admin/login'
    | '/admin/atracoes'
    | '/admin/calendario'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/home'
    | '/admin/instagram'
    | '/admin/propriedades'
    | '/admin/reservas'
    | '/admin/sobre'
    | '/admin/submissoes'
    | '/atracoes/$slug'
    | '/imovel/$slug'
    | '/passeios/$slug'
    | '/restaurantes/$slug'
    | '/admin/'
    | '/atracoes/'
    | '/passeios/'
    | '/restaurantes/'
    | '/admin/propriedades/nova'
    | '/admin/reservas/$id'
    | '/admin/reservas/nova'
    | '/admin/propriedades/'
    | '/admin/reservas/'
    | '/admin/propriedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/eventos'
    | '/propriedades'
    | '/sobre'
    | '/admin/login'
    | '/admin/atracoes'
    | '/admin/calendario'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/home'
    | '/admin/instagram'
    | '/admin/sobre'
    | '/admin/submissoes'
    | '/atracoes/$slug'
    | '/imovel/$slug'
    | '/passeios/$slug'
    | '/restaurantes/$slug'
    | '/admin'
    | '/atracoes'
    | '/passeios'
    | '/restaurantes'
    | '/admin/propriedades/nova'
    | '/admin/reservas/$id'
    | '/admin/reservas/nova'
    | '/admin/propriedades'
    | '/admin/reservas'
    | '/admin/propriedades/$id/editar'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/_admin/admin'
    | '/_public/anuncie'
    | '/_public/eventos'
    | '/_public/propriedades'
    | '/_public/sobre'
    | '/admin/login'
    | '/_public/'
    | '/_admin/admin/atracoes'
    | '/_admin/admin/calendario'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/eventos'
    | '/_admin/admin/home'
    | '/_admin/admin/instagram'
    | '/_admin/admin/propriedades'
    | '/_admin/admin/reservas'
    | '/_admin/admin/sobre'
    | '/_admin/admin/submissoes'
    | '/_public/atracoes/$slug'
    | '/_public/imovel/$slug'
    | '/_public/passeios/$slug'
    | '/_public/restaurantes/$slug'
    | '/_admin/admin/'
    | '/_public/atracoes/'
    | '/_public/passeios/'
    | '/_public/restaurantes/'
    | '/_admin/admin/propriedades/nova'
    | '/_admin/admin/reservas/$id'
    | '/_admin/admin/reservas/nova'
    | '/_admin/admin/propriedades/'
    | '/_admin/admin/reservas/'
    | '/_admin/admin/propriedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/propriedades': {
      id: '/_public/propriedades'
      path: '/propriedades'
      fullPath: '/propriedades'
      preLoaderRoute: typeof PublicPropriedadesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/eventos': {
      id: '/_public/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof PublicEventosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/anuncie': {
      id: '/_public/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof PublicAnuncieRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/restaurantes/': {
      id: '/_public/restaurantes/'
      path: '/restaurantes'
      fullPath: '/restaurantes/'
      preLoaderRoute: typeof PublicRestaurantesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/passeios/': {
      id: '/_public/passeios/'
      path: '/passeios'
      fullPath: '/passeios/'
      preLoaderRoute: typeof PublicPasseiosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/atracoes/': {
      id: '/_public/atracoes/'
      path: '/atracoes'
      fullPath: '/atracoes/'
      preLoaderRoute: typeof PublicAtracoesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_public/restaurantes/$slug': {
      id: '/_public/restaurantes/$slug'
      path: '/restaurantes/$slug'
      fullPath: '/restaurantes/$slug'
      preLoaderRoute: typeof PublicRestaurantesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/passeios/$slug': {
      id: '/_public/passeios/$slug'
      path: '/passeios/$slug'
      fullPath: '/passeios/$slug'
      preLoaderRoute: typeof PublicPasseiosSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/imovel/$slug': {
      id: '/_public/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof PublicImovelSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/atracoes/$slug': {
      id: '/_public/atracoes/$slug'
      path: '/atracoes/$slug'
      fullPath: '/atracoes/$slug'
      preLoaderRoute: typeof PublicAtracoesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/submissoes': {
      id: '/_admin/admin/submissoes'
      path: '/submissoes'
      fullPath: '/admin/submissoes'
      preLoaderRoute: typeof AdminAdminSubmissoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/sobre': {
      id: '/_admin/admin/sobre'
      path: '/sobre'
      fullPath: '/admin/sobre'
      preLoaderRoute: typeof AdminAdminSobreRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reservas': {
      id: '/_admin/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminAdminReservasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/propriedades': {
      id: '/_admin/admin/propriedades'
      path: '/propriedades'
      fullPath: '/admin/propriedades'
      preLoaderRoute: typeof AdminAdminPropriedadesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/instagram': {
      id: '/_admin/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminAdminInstagramRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/home': {
      id: '/_admin/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminAdminHomeRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/eventos': {
      id: '/_admin/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminAdminEventosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/calendario': {
      id: '/_admin/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminAdminCalendarioRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/atracoes': {
      id: '/_admin/admin/atracoes'
      path: '/atracoes'
      fullPath: '/admin/atracoes'
      preLoaderRoute: typeof AdminAdminAtracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reservas/': {
      id: '/_admin/admin/reservas/'
      path: '/'
      fullPath: '/admin/reservas/'
      preLoaderRoute: typeof AdminAdminReservasIndexRouteImport
      parentRoute: typeof AdminAdminReservasRoute
    }
    '/_admin/admin/propriedades/': {
      id: '/_admin/admin/propriedades/'
      path: '/'
      fullPath: '/admin/propriedades/'
      preLoaderRoute: typeof AdminAdminPropriedadesIndexRouteImport
      parentRoute: typeof AdminAdminPropriedadesRoute
    }
    '/_admin/admin/reservas/nova': {
      id: '/_admin/admin/reservas/nova'
      path: '/nova'
      fullPath: '/admin/reservas/nova'
      preLoaderRoute: typeof AdminAdminReservasNovaRouteImport
      parentRoute: typeof AdminAdminReservasRoute
    }
    '/_admin/admin/reservas/$id': {
      id: '/_admin/admin/reservas/$id'
      path: '/$id'
      fullPath: '/admin/reservas/$id'
      preLoaderRoute: typeof AdminAdminReservasIdRouteImport
      parentRoute: typeof AdminAdminReservasRoute
    }
    '/_admin/admin/propriedades/nova': {
      id: '/_admin/admin/propriedades/nova'
      path: '/nova'
      fullPath: '/admin/propriedades/nova'
      preLoaderRoute: typeof AdminAdminPropriedadesNovaRouteImport
      parentRoute: typeof AdminAdminPropriedadesRoute
    }
    '/_admin/admin/propriedades/$id/editar': {
      id: '/_admin/admin/propriedades/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/propriedades/$id/editar'
      preLoaderRoute: typeof AdminAdminPropriedadesIdEditarRouteImport
      parentRoute: typeof AdminAdminPropriedadesRoute
    }
  }
}

interface AdminAdminPropriedadesRouteChildren {
  AdminAdminPropriedadesNovaRoute: typeof AdminAdminPropriedadesNovaRoute
  AdminAdminPropriedadesIndexRoute: typeof AdminAdminPropriedadesIndexRoute
  AdminAdminPropriedadesIdEditarRoute: typeof AdminAdminPropriedadesIdEditarRoute
}

const AdminAdminPropriedadesRouteChildren: AdminAdminPropriedadesRouteChildren =
  {
    AdminAdminPropriedadesNovaRoute: AdminAdminPropriedadesNovaRoute,
    AdminAdminPropriedadesIndexRoute: AdminAdminPropriedadesIndexRoute,
    AdminAdminPropriedadesIdEditarRoute: AdminAdminPropriedadesIdEditarRoute,
  }

const AdminAdminPropriedadesRouteWithChildren =
  AdminAdminPropriedadesRoute._addFileChildren(
    AdminAdminPropriedadesRouteChildren,
  )

interface AdminAdminReservasRouteChildren {
  AdminAdminReservasIdRoute: typeof AdminAdminReservasIdRoute
  AdminAdminReservasNovaRoute: typeof AdminAdminReservasNovaRoute
  AdminAdminReservasIndexRoute: typeof AdminAdminReservasIndexRoute
}

const AdminAdminReservasRouteChildren: AdminAdminReservasRouteChildren = {
  AdminAdminReservasIdRoute: AdminAdminReservasIdRoute,
  AdminAdminReservasNovaRoute: AdminAdminReservasNovaRoute,
  AdminAdminReservasIndexRoute: AdminAdminReservasIndexRoute,
}

const AdminAdminReservasRouteWithChildren =
  AdminAdminReservasRoute._addFileChildren(AdminAdminReservasRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminAtracoesRoute: typeof AdminAdminAtracoesRoute
  AdminAdminCalendarioRoute: typeof AdminAdminCalendarioRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminEventosRoute: typeof AdminAdminEventosRoute
  AdminAdminHomeRoute: typeof AdminAdminHomeRoute
  AdminAdminInstagramRoute: typeof AdminAdminInstagramRoute
  AdminAdminPropriedadesRoute: typeof AdminAdminPropriedadesRouteWithChildren
  AdminAdminReservasRoute: typeof AdminAdminReservasRouteWithChildren
  AdminAdminSobreRoute: typeof AdminAdminSobreRoute
  AdminAdminSubmissoesRoute: typeof AdminAdminSubmissoesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAtracoesRoute: AdminAdminAtracoesRoute,
  AdminAdminCalendarioRoute: AdminAdminCalendarioRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminEventosRoute: AdminAdminEventosRoute,
  AdminAdminHomeRoute: AdminAdminHomeRoute,
  AdminAdminInstagramRoute: AdminAdminInstagramRoute,
  AdminAdminPropriedadesRoute: AdminAdminPropriedadesRouteWithChildren,
  AdminAdminReservasRoute: AdminAdminReservasRouteWithChildren,
  AdminAdminSobreRoute: AdminAdminSobreRoute,
  AdminAdminSubmissoesRoute: AdminAdminSubmissoesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicAnuncieRoute: typeof PublicAnuncieRoute
  PublicEventosRoute: typeof PublicEventosRoute
  PublicPropriedadesRoute: typeof PublicPropriedadesRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAtracoesSlugRoute: typeof PublicAtracoesSlugRoute
  PublicImovelSlugRoute: typeof PublicImovelSlugRoute
  PublicPasseiosSlugRoute: typeof PublicPasseiosSlugRoute
  PublicRestaurantesSlugRoute: typeof PublicRestaurantesSlugRoute
  PublicAtracoesIndexRoute: typeof PublicAtracoesIndexRoute
  PublicPasseiosIndexRoute: typeof PublicPasseiosIndexRoute
  PublicRestaurantesIndexRoute: typeof PublicRestaurantesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAnuncieRoute: PublicAnuncieRoute,
  PublicEventosRoute: PublicEventosRoute,
  PublicPropriedadesRoute: PublicPropriedadesRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAtracoesSlugRoute: PublicAtracoesSlugRoute,
  PublicImovelSlugRoute: PublicImovelSlugRoute,
  PublicPasseiosSlugRoute: PublicPasseiosSlugRoute,
  PublicRestaurantesSlugRoute: PublicRestaurantesSlugRoute,
  PublicAtracoesIndexRoute: PublicAtracoesIndexRoute,
  PublicPasseiosIndexRoute: PublicPasseiosIndexRoute,
  PublicRestaurantesIndexRoute: PublicRestaurantesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
